lab 4 :

In [29]:
import numpy as np
import matplotlib.pyplot as plt


median ()mean() argmin

letra a

In [30]:
array=np.arange(1,11)
array




array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

letra b

In [31]:
arrayaleatorio=np.random.randint(1,21,10)
arrayaleatorio

array([ 9, 10, 16,  9,  1,  2, 12,  2,  6, 10])

letra c

In [32]:
suma=(array+arrayaleatorio)
suma

array([10, 12, 19, 13,  6,  8, 19, 10, 15, 20])

letra d

In [33]:
aleatorio=np.random.shuffle(suma)
aleatorio

In [34]:
suma

array([20, 19, 19, 12, 10,  8, 10, 15, 13,  6])

letra e

In [35]:
#calcular mediana promedio
mediana=np.median(suma)

In [36]:
#promedio
promedio=np.mean(suma)
promedio

13.2

In [37]:
#minimo
min=np.argmin(suma)
min



9

In [38]:
#maximo
max=np.argmax(suma)
max

0

letra f

In [41]:
#tranformar vector a matriz

matriz=suma.reshape(2,5)
matriz


array([[20, 19, 19, 12, 10],
       [ 8, 10, 15, 13,  6]])